# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestSDKDemo_Dy_All' do
#  引入MBProgressHUD 则控制台会输出类重复警告
#  pod 'MBProgressHUD', '1.2.0'
end
target 'TestSDKDemo_Dy_RemoveMB' do
  #use_frameworks!  #可用可不用
  pod 'MBProgressHUD', '1.2.0'
end
target 'TestSDKDemo_Dy_RemoveAll' do
  # 必须使用use_frameworks
  use_frameworks!
  pod 'MBProgressHUD', '1.2.0'
end
target 'TestSDKDemo_Static' do
  #use_frameworks!  打包时需用.a引入私有组件，此处若使用use_frameworks，会找不到方法崩溃
  pod 'MBProgressHUD', '1.2.0'
end
